// Generated by Latch 0.1.0. Edit latch.config.json and application handlers, then regenerate.
import { useLatch, type ScopeObserver } from '@latch-local/react';
import type { Handler, Contract } from '@latch-local/contracts';
import { searchDocs as handler0 } from "../library";
import { readDocs as handler1 } from "../library";
import { openDoc as handler2 } from "../library";
export type Input0 = { "text"?: string };
export type Result0 = { "query": string; "matches": Array<{ "id": string; "title": string; "body": string }>; "openedId": string };
export type Input1 = {  };
export type Result1 = { "query": string; "matches": Array<{ "id": string; "title": string; "body": string }>; "openedId": string };
export type Input2 = { "id": string };
export type Result2 = { "query": string; "matches": Array<{ "id": string; "title": string; "body": string }>; "openedId": string };
export interface ReactHandlers {}
export const contracts: Contract[] = [
  {
    "name": "docs.search",
    "description": "Search fixture documentation by text. Omitted text preserves the query; empty text resets.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "text": {
          "type": "string",
          "maxLength": 120
        }
      },
      "required": [],
      "additionalProperties": false
    },
    "resultSchema": {
      "type": "object",
      "properties": {
        "query": {
          "type": "string"
        },
        "matches": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "body": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "title",
              "body"
            ],
            "additionalProperties": false
          },
          "maxItems": 100
        },
        "openedId": {
          "type": "string"
        }
      },
      "required": [
        "query",
        "matches",
        "openedId"
      ],
      "additionalProperties": false
    },
    "scope": {
      "route": "/",
      "component": "App"
    },
    "preconditions": [],
    "sideEffects": "ui"
  },
  {
    "name": "docs.read",
    "description": "Read visible documentation matches and opened document.",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "required": [],
      "additionalProperties": false
    },
    "resultSchema": {
      "type": "object",
      "properties": {
        "query": {
          "type": "string"
        },
        "matches": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "body": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "title",
              "body"
            ],
            "additionalProperties": false
          },
          "maxItems": 100
        },
        "openedId": {
          "type": "string"
        }
      },
      "required": [
        "query",
        "matches",
        "openedId"
      ],
      "additionalProperties": false
    },
    "scope": {
      "route": "/",
      "component": "App"
    },
    "preconditions": [],
    "sideEffects": "none"
  },
  {
    "name": "docs.open",
    "description": "Open a currently visible document. Invalid IDs reject without a state change.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "minLength": 1,
          "maxLength": 100
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "resultSchema": {
      "type": "object",
      "properties": {
        "query": {
          "type": "string"
        },
        "matches": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "body": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "title",
              "body"
            ],
            "additionalProperties": false
          },
          "maxItems": 100
        },
        "openedId": {
          "type": "string"
        }
      },
      "required": [
        "query",
        "matches",
        "openedId"
      ],
      "additionalProperties": false
    },
    "scope": {
      "route": "/",
      "component": "App"
    },
    "preconditions": [],
    "sideEffects": "ui"
  }
];
let devObserver: ScopeObserver | undefined;
if (import.meta.env.DEV) {
  const { attachBridge } = await import('@latch-local/test/bridge');
  devObserver = scope => location.origin === "http://127.0.0.1:5174" ? attachBridge(scope, ["http://127.0.0.1:5174"]) : undefined;
}
export function useProjectTools(handlers: ReactHandlers) {
  useLatch([{contract: contracts[0], handler: handler0},
{contract: contracts[1], handler: handler1},
{contract: contracts[2], handler: handler2}], { scopeKey: "/:App|/:App|/:App", onScope: devObserver });
}
const verify0: Handler<Input0, Result0> = handler0;
void verify0;
const verify1: Handler<Input1, Result1> = handler1;
void verify1;
const verify2: Handler<Input2, Result2> = handler2;
void verify2;