// Generated by Latch 0.1.0. Edit latch.config.json and application handlers, then regenerate.
import { useLatch, type ScopeObserver } from '@latch-local/react';
import type { Handler, Contract } from '@latch-local/contracts';
export type Input0 = { "query"?: string; "category"?: "all" | "workspace" | "outdoors"; "sort"?: "name" | "price-asc" | "price-desc" };
export type Result0 = { "query": string; "category": string; "sort": string; "items": Array<{ "id": string; "name": string; "category": string; "price": number }>; "selectedId": string };
export type Input1 = {  };
export type Result1 = { "query": string; "category": string; "sort": string; "items": Array<{ "id": string; "name": string; "category": string; "price": number }>; "selectedId": string };
export type Input2 = { "id": string };
export type Result2 = { "query": string; "category": string; "sort": string; "items": Array<{ "id": string; "name": string; "category": string; "price": number }>; "selectedId": string };
export interface ReactHandlers {"catalog.search": Handler<Input0, Result0>;
"catalog.read": Handler<Input1, Result1>;
"catalog.details": Handler<Input2, Result2>}
export const contracts: Contract[] = [
  {
    "name": "catalog.search",
    "description": "Search visible catalog items. Omitted fields preserve current values; empty query, all category and name sort reset them. Await completion before reading state.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "query": {
          "type": "string",
          "maxLength": 120
        },
        "category": {
          "type": "string",
          "enum": [
            "all",
            "workspace",
            "outdoors"
          ]
        },
        "sort": {
          "type": "string",
          "enum": [
            "name",
            "price-asc",
            "price-desc"
          ]
        }
      },
      "required": [],
      "additionalProperties": false
    },
    "resultSchema": {
      "type": "object",
      "properties": {
        "query": {
          "type": "string"
        },
        "category": {
          "type": "string"
        },
        "sort": {
          "type": "string"
        },
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "category": {
                "type": "string"
              },
              "price": {
                "type": "number"
              }
            },
            "required": [
              "id",
              "name",
              "category",
              "price"
            ],
            "additionalProperties": false
          },
          "maxItems": 100
        },
        "selectedId": {
          "type": "string"
        }
      },
      "required": [
        "query",
        "category",
        "sort",
        "items",
        "selectedId"
      ],
      "additionalProperties": false
    },
    "scope": {
      "route": "/",
      "component": "Catalog"
    },
    "preconditions": [],
    "sideEffects": "ui"
  },
  {
    "name": "catalog.read",
    "description": "Read the currently visible catalog results and selected item without changing state.",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "required": [],
      "additionalProperties": false
    },
    "resultSchema": {
      "type": "object",
      "properties": {
        "query": {
          "type": "string"
        },
        "category": {
          "type": "string"
        },
        "sort": {
          "type": "string"
        },
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "category": {
                "type": "string"
              },
              "price": {
                "type": "number"
              }
            },
            "required": [
              "id",
              "name",
              "category",
              "price"
            ],
            "additionalProperties": false
          },
          "maxItems": 100
        },
        "selectedId": {
          "type": "string"
        }
      },
      "required": [
        "query",
        "category",
        "sort",
        "items",
        "selectedId"
      ],
      "additionalProperties": false
    },
    "scope": {
      "route": "/",
      "component": "Catalog"
    },
    "preconditions": [],
    "sideEffects": "none"
  },
  {
    "name": "catalog.details",
    "description": "Open details for a currently visible item; unknown or hidden IDs fail without changes.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "minLength": 1,
          "maxLength": 100
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "resultSchema": {
      "type": "object",
      "properties": {
        "query": {
          "type": "string"
        },
        "category": {
          "type": "string"
        },
        "sort": {
          "type": "string"
        },
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "category": {
                "type": "string"
              },
              "price": {
                "type": "number"
              }
            },
            "required": [
              "id",
              "name",
              "category",
              "price"
            ],
            "additionalProperties": false
          },
          "maxItems": 100
        },
        "selectedId": {
          "type": "string"
        }
      },
      "required": [
        "query",
        "category",
        "sort",
        "items",
        "selectedId"
      ],
      "additionalProperties": false
    },
    "scope": {
      "route": "/",
      "component": "Catalog"
    },
    "preconditions": [],
    "sideEffects": "ui"
  }
];
let devObserver: ScopeObserver | undefined;
if (import.meta.env.DEV) {
  const { attachBridge } = await import('@latch-local/test/bridge');
  devObserver = scope => location.origin === "http://127.0.0.1:5173" ? attachBridge(scope, ["http://127.0.0.1:5173"]) : undefined;
}
export function useProjectTools(handlers: ReactHandlers) {
  useLatch([{contract: contracts[0], handler: handlers["catalog.search"]},
{contract: contracts[1], handler: handlers["catalog.read"]},
{contract: contracts[2], handler: handlers["catalog.details"]}], { scopeKey: "/:Catalog|/:Catalog|/:Catalog", onScope: devObserver });
}


